name: 'Robert Myers, Psychotherapist'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.809685
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: 'Robert Myers, Psychotherapist '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.507883
  saturation: 0.596847
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
