analytics: {}
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 0.506757
  rhythmicContrast: 0.803225
  saturation: 0.544355
cta: {}
layout_spectrum: 0.576577
name: 'Robert Myers, Psychotherapist'
opengraph: {}
purpose: {}
typography_spectrum: 0.796171
