analytics: {}
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 0.47973
  lightness: 0.992117
  rhythmicContrast: 0
  saturation: 1
cta: {}
layout_spectrum: 0.876126
name: 'Robert Myers, Psychotherapist'
opengraph: {}
purpose: {}
typography_spectrum: 0.809685
