name: 'Robert Myers, Psychotherapist'
favicon: null
layout_spectrum: 0.876126
typography_spectrum: 0.809685
title: 'Robert Myers, Psychotherapist * Solution Focused, Depth Therapy for Individuals, Couples, and Families * Portland, ME'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 0.152027
  lightness: 0.992117
  saturation: 1
  rhythmicContrast: 0.243243
purpose:
  - name: null
    item: null
    url: null
