typography_spectrum: 0.5640077027492225
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.507883
  saturation: 0.596847
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6195534768048674
analytics:
  google: UA-83312363-1
  facebook: null
  twitter: null
author:
  name: 'Robert Myers, LCPC'
  email: robert@robertmyerslcpc.com
  url: 'http://www.robertmyerslcpc.com'
name: 'Robert Myers, Psychotherapist '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Credentials
    id: ce55ef68-5b81-4a85-89ff-32cad7e6cd60
    type: content
  - name: 'Fees, Insurance, Protocols'
    id: b2e34ff5-b953-4631-9bd8-107e1ae31386
    type: content
  - name: Course of Treatment
    id: a11fe776-d964-4ea0-a419-3fe9daea9ac2
    type: content
  - name: Contact
    id: de44d5cb-d271-450c-b50c-ac21c802d5c3
    type: content
  - name: Links
    id: 546a9bae-9e11-49d2-ba44-530caa1d0e4f
    type: content
  - name: Blog
    url: 'https://robertmyerslcpc.wordpress.com/'
    type: external
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: 'Robert Myers, Psychotherapist '
description: >-
  Solution Focused, Depth Psychotherapy for Individuals, Couples, and Families |
  Portland, Maine
purpose: []
