analytics: {}
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.546171
cta: {}
layout_spectrum: 0
name: 'Robert Myers, Psychotherapist'
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.809685
