layout_spectrum: 0.1045056
name: 'Robert Myers, Psychotherapist'
purpose:
  - {}
analytics: {}
opengraph: {}
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta: {}
color:
  brandStrength: 0
  saturation: 0.596847
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  lightness: 0.507883
  rhythmicContrast: 0
typography_spectrum: 0.809685
