analytics: {}
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 0.601351
  lightness: 0.763514
  rhythmicContrast: 0.634009
  saturation: 0.834459
cta: {}
layout_spectrum: 0.876126
name: 'Robert Myers, Psychotherapist'
opengraph: {}
purpose: {}
typography_spectrum: 0.809685
